#  * Cargo.toml
#  * Copyright (C) 2024–2025 Parsicore <parsicore.dev@gmail.com>
#  * Sign: mitra-20250419-bd5fbe728fa2-5836b45f25d83501625cc5529193d5f0

[workspace]
members = [
    "mitra-cli",
    "mitra-core",
    "mitra-gui", 
]
resolver = "2"
