#  * Cargo.toml
#  * Copyright (C) Mohammad (Sina) Jalalvandi (parsidate) 2024-2025 <jalalvandi.sina@gmail.com>
#  * Version : 1.1.0
#  * 714b5631-87ad-4fde-905f-89dc149387f2

[package]
name = "mitra"
version = "1.1.0"
edition = "2024"
description = "A versatile command-line interface (CLI) tool for working with Persian (Jalali/Shamsi) dates and times, built upon the robust parsidate"
license = "Apache-2.0"
authors = ["Sina Jalalvandi <Jalalvandi.Sina@gmail.com>"] 
readme = "README.md"
repository = "https://github.com/jalalvandi/mitra"

[dependencies]
parsidate = "1.4.0"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
chrono = "0.4"

