# ~/mitra-gui/Cargo.toml

[package]
name = "mitra-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
# The Iced GUI library
iced = { version = "0.12", features = ["tokio", "debug"] }

# Our core logic library
mitra-core = { path = "../mitra-core" }