# .github/workflows/ci.yml
name: Continuous Integration

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - '**/*.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    branches: [ "main", "master" ]
    paths:
      - '**/*.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  check_and_lint:
    name: Check & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Check formatting
        run: cargo fmt --all -- --check

  build_and_test:
    name: Build & Test
    runs-on: ${{ matrix.os }}
    needs: [check_and_lint]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain (${{ matrix.rust }})
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}

      - name: Cache Cargo Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build project
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
